name: Track updates

on:
    schedule:
        - cron: '*/5 * * * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
            pull-requests: write
            issues: write
            statuses: write
            deployments: write

        steps:
            - name: Checkout discord_android branch
              uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '24.x'

            - name: Run script
              run: node track.mjs
              env:
                KEY: ${{ secrets.KEY }}
                API_URL: ${{ secrets.API_URL }}
                WEBHOOK: ${{ secrets.WEBHOOK }}
              
            - name: Set git identity
              run: |
                  git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --local user.name "github-actions[bot]"

            - name: Commit & push changes
              run: |
                  git add --all
                  git diff-index --quiet HEAD || git commit -am "chore: update info.json"
                  git push
